<?php
/**
 * Demo: CODE_RANDOM_COMPLEX with NEW Unified Schema
 */

require_once __DIR__ . '/../config/database.php';

$conn = getDbConnection();

// Find or create assignment
$assignmentTitle = 'CODE_RANDOM_COMPLEX Unified Schema Demo';
$stmt = $conn->prepare('SELECT id FROM assignments WHERE title = ? LIMIT 1');
$stmt->bind_param('s', $assignmentTitle);
$stmt->execute();
$result = $stmt->get_result();

$assignmentId = null;
if ($row = $result->fetch_assoc()) {
    $assignmentId = $row['id'];
    echo "Using existing assignment: $assignmentId\n";
} else {
    $userId = 1;
    $stmt = $conn->prepare('INSERT INTO assignments (title, description, created_by, is_active) VALUES (?, ?, ?, 1)');
    $description = 'Demonstration of new unified CODE_RANDOM_COMPLEX schema';
    $stmt->bind_param('ssi', $assignmentTitle, $description, $userId);
    $stmt->execute();
    $assignmentId = $stmt->insert_id;
    echo "Created new assignment: $assignmentId\n";
}

// Clear existing tasks
$stmt = $conn->prepare('DELETE FROM tasks WHERE assignment_id = ?');
$stmt->bind_param('i', $assignmentId);
$stmt->execute();

// Task 1: Binary to Decimal
$position = 1;
$title = 'Binary to Decimal (Unified Demo)';
$description = 'Convert 8-bit binary to decimal with randomized values';
$taskType = 'code_random_complex';
$taskText = 'Given a random 8-bit binary number, convert it to decimal';
$questionText = 'What is the decimal value?';
$codeTemplate = 'result = int(values["binary"], 2)';
$solutionCode = 'result = int(values["binary"], 2)';
$correctAnswer = 'result';
$variableOverrides = json_encode([["inputs" => ["binary" => "<random>"], "expected" => ["variable" => "result"]]]);
$randomizerCode = "import random\nbinary = format(random.randint(0, 255), '08b')\nvalues = {'binary': binary}";
$maxAttempts = 1;
$iterationsCount = 5;
$showSolution = 1;
$showSolutionCode = 1;

$stmt = $conn->prepare('INSERT INTO tasks (assignment_id, position, title, description, task_type, task_text, question_text, code_template, solution_code, correct_answer, variable_overrides, randomizer_code, max_attempts, iterations_count, show_solution, show_solution_code) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');

$stmt->bind_param('iissssssssssiiii', $assignmentId, $position, $title, $description, $taskType, $taskText, $questionText, $codeTemplate, $solutionCode, $correctAnswer, $variableOverrides, $randomizerCode, $maxAttempts, $iterationsCount, $showSolution, $showSolutionCode);

if ($stmt->execute()) {
    echo "✓ Task 1 created (ID: {$stmt->insert_id})\n";
} else {
    echo "✗ Task 1 error: " . $stmt->error . "\n";
}

// Task 2: Celsius to Fahrenheit
$position = 2;
$title = 'Celsius to Fahrenheit (Unified Demo)';
$description = 'Convert Celsius to Fahrenheit with randomized temperature';
$taskType = 'code_random_complex';
$taskText = 'Convert random Celsius value to Fahrenheit: F = (C × 9/5) + 32';
$questionText = 'What is the Fahrenheit value?';
$codeTemplate = 'fahrenheit = (values["celsius"] * 9/5) + 32';
$solutionCode = 'fahrenheit = (values["celsius"] * 9/5) + 32';
$correctAnswer = 'fahrenheit';
$variableOverrides = json_encode([["inputs" => ["celsius" => "<random>"], "expected" => ["variable" => "fahrenheit"]]]);
$randomizerCode = "import random\ncelsius = random.randint(-50, 50)\nvalues = {'celsius': celsius}";
$maxAttempts = 1;
$iterationsCount = 3;
$showSolution = 1;
$showSolutionCode = 1;

$stmt = $conn->prepare('INSERT INTO tasks (assignment_id, position, title, description, task_type, task_text, question_text, code_template, solution_code, correct_answer, variable_overrides, randomizer_code, max_attempts, iterations_count, show_solution, show_solution_code) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');

$stmt->bind_param('iissssssssssiiii', $assignmentId, $position, $title, $description, $taskType, $taskText, $questionText, $codeTemplate, $solutionCode, $correctAnswer, $variableOverrides, $randomizerCode, $maxAttempts, $iterationsCount, $showSolution, $showSolutionCode);

if ($stmt->execute()) {
    echo "✓ Task 2 created (ID: {$stmt->insert_id})\n";
} else {
    echo "✗ Task 2 error: " . $stmt->error . "\n";
}

echo "\n=== Summary ===\n";
echo "Assignment ID: $assignmentId\n";
echo "Assignment Title: $assignmentTitle\n\n";
echo "✓ Demo tasks created successfully!\n\n";
echo "New Unified variable_overrides Structure:\n";
$demo = json_encode(json_decode($variableOverrides, true), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
echo $demo . "\n\n";
echo "Key Features:\n";
echo "  • variable_overrides: Unified between CODE_READING and CODE_RANDOM_COMPLEX\n";
echo "  • <random> markers: Indicate values to be generated by randomizer_code\n";
echo "  • expected.variable: Auto mode extracts variable from solution_code\n";
echo "  • randomizer_code: Separate field for generating random input values\n";
echo "  • max_iterations: Each iteration generates NEW random values\n";
?>
